#############################################################################
# Makefile for building: CincoHuevitos
# Generated by qmake (1.07a) (Qt 3.3.8b) on: Wed Sep 24 09:05:11 2008
# Project:  CincoHuevitos.pro
# Template: app
# Command: $(QMAKE) -o Makefile CincoHuevitos.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
CXXFLAGS = -pipe -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/share/qt3/mkspecs/default -I. -I. -I/usr/include/qt3
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L/usr/share/qt3/lib -L/usr/X11R6/lib -lqt-mt -lXext -lX11 -lm -lpthread
AR       = ar cqs
RANLIB   = 
MOC      = /usr/share/qt3/bin/moc
UIC      = /usr/share/qt3/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = Alineacion.h \
		ArchivoJuego.h \
		BuscarCamino.h \
		CincoHuevitosGUI.h \
		Matriz.h \
		Operaciones.h
SOURCES = Alineacion.cpp \
		ArchivoJuego.cpp \
		BuscarCamino.cpp \
		CincoHuevitosGUI.cpp \
		Matriz.cpp \
		Operaciones.cpp
OBJECTS = Alineacion.o \
		ArchivoJuego.o \
		BuscarCamino.o \
		CincoHuevitosGUI.o \
		Matriz.o \
		Operaciones.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = moc_CincoHuevitosGUI.cpp
OBJMOC = moc_CincoHuevitosGUI.o
DIST	   = CincoHuevitos.pro
QMAKE_TARGET = CincoHuevitos
DESTDIR  = 
TARGET   = CincoHuevitos

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: CincoHuevitos.pro  /usr/share/qt3/mkspecs/default/qmake.conf /usr/share/qt3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile CincoHuevitos.pro
qmake: 
	@$(QMAKE) -o Makefile CincoHuevitos.pro

dist: 
	@mkdir -p .tmp/CincoHuevitos && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/CincoHuevitos/ && ( cd `dirname .tmp/CincoHuevitos` && $(TAR) CincoHuevitos.tar CincoHuevitos && $(GZIP) CincoHuevitos.tar ) && $(MOVE) `dirname .tmp/CincoHuevitos`/CincoHuevitos.tar.gz . && $(DEL_FILE) -r .tmp/CincoHuevitos

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:

yaccclean:
lexclean:
clean: mocclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

Alineacion.o: Alineacion.cpp Alineacion.h

ArchivoJuego.o: ArchivoJuego.cpp ArchivoJuego.h

BuscarCamino.o: BuscarCamino.cpp BuscarCamino.h

CincoHuevitosGUI.o: CincoHuevitosGUI.cpp CincoHuevitosGUI.h \
		Operaciones.h \
		Matriz.h \
		BuscarCamino.h \
		Alineacion.h \
		ArchivoJuego.h

Matriz.o: Matriz.cpp Matriz.h

Operaciones.o: Operaciones.cpp Operaciones.h \
		Matriz.h \
		BuscarCamino.h \
		Alineacion.h \
		ArchivoJuego.h

moc_CincoHuevitosGUI.o: moc_CincoHuevitosGUI.cpp  CincoHuevitosGUI.h Operaciones.h \
		Matriz.h \
		BuscarCamino.h \
		Alineacion.h \
		ArchivoJuego.h

moc_CincoHuevitosGUI.cpp: $(MOC) CincoHuevitosGUI.h
	$(MOC) CincoHuevitosGUI.h -o moc_CincoHuevitosGUI.cpp

####### Install

install:  

uninstall:  

